# Generated by Erlang.mk. Edit at your own risk!

src/gif_handler.erl:: src/include/model/giphy_table_definitions.hrl; @touch $@
src/giphy_table_mngr.erl:: src/include/model/giphy_table_definitions.hrl; @touch $@

COMPILE_FIRST +=
